<Project>

  <Target Name="LogTest" BeforeTargets="Build" Condition="$(TargetFramework) != ''">
      <Message Importance="High" Text="✅ LogTest target 실행됨! Framework=$(TargetFramework)" />
  </Target>
    
  <Target Name="IncludeXmlForPack" AfterTargets="Build" Condition=" '$(TargetFramework)' != '' ">
    <Message Importance="High" Text="IncludeXmlForPack target is running for $(TargetFramework)" />
    <Message Importance="High" Text="IncludeXmlForPack target is running for $(MSBuildProjectDirectory)" />
    <ItemGroup>
      <None Include="$(MSBuildProjectDirectory)Documents\SimpleOverlayTheme.kr.xml">
        <Pack>True</Pack>
        <PackagePath>lib\$(TargetFramework)\kr\SimpleOverlayTheme.xml</PackagePath>
        <IncludeInPackage>true</IncludeInPackage>
          <Visible>true</Visible>
      </None >
    </ItemGroup>

  </Target>
</Project>
