//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleOverlayTheme.Theme.ThemeDictionary {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThemeDictionaryKey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThemeDictionaryKey() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleOverlayTheme.Theme.ThemeDictionary.ThemeDictionaryKey", typeof(ThemeDictionaryKey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Background과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Background {
            get {
                return ResourceManager.GetString("ColorPalette_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Foreground과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Foreground {
            get {
                return ResourceManager.GetString("ColorPalette_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Foreground_Disable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Foreground_Disable {
            get {
                return ResourceManager.GetString("ColorPalette_Foreground_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Highlight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Highlight {
            get {
                return ResourceManager.GetString("ColorPalette_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Line {
            get {
                return ResourceManager.GetString("ColorPalette_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Mask과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Mask {
            get {
                return ResourceManager.GetString("ColorPalette_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Outline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Outline {
            get {
                return ResourceManager.GetString("ColorPalette_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultBrush.Selection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColorPalette_Selection {
            get {
                return ResourceManager.GetString("ColorPalette_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.FontSize.Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FontSize_Default {
            get {
                return ResourceManager.GetString("FontSize_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.FontSize.Header1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FontSize_Header1 {
            get {
                return ResourceManager.GetString("FontSize_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.FontSize.Header2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FontSize_Header2 {
            get {
                return ResourceManager.GetString("FontSize_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.FontSize.Header3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FontSize_Header3 {
            get {
                return ResourceManager.GetString("FontSize_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.FontSize.Header4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FontSize_Header4 {
            get {
                return ResourceManager.GetString("FontSize_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.FontSize.Header5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FontSize_Header5 {
            get {
                return ResourceManager.GetString("FontSize_Header5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.FontSize.Header6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FontSize_Header6 {
            get {
                return ResourceManager.GetString("FontSize_Header6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Background.Active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderBackground_Active {
            get {
                return ResourceManager.GetString("OverlayBorderBackground_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Background.Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderBackground_Default {
            get {
                return ResourceManager.GetString("OverlayBorderBackground_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Background.Disable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderBackground_Disable {
            get {
                return ResourceManager.GetString("OverlayBorderBackground_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Background.MouseOver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderBackground_MouseOver {
            get {
                return ResourceManager.GetString("OverlayBorderBackground_MouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Outline.Active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderOutline_Active {
            get {
                return ResourceManager.GetString("OverlayBorderOutline_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Outline.Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderOutline_Default {
            get {
                return ResourceManager.GetString("OverlayBorderOutline_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Outline.Disable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderOutline_Disable {
            get {
                return ResourceManager.GetString("OverlayBorderOutline_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayBoader.Outline.MouseOver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayBorderOutline_MouseOver {
            get {
                return ResourceManager.GetString("OverlayBorderOutline_MouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayMask.Foreground.Active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayMaskForeground_Active {
            get {
                return ResourceManager.GetString("OverlayMaskForeground_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayMask.Foreground.Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayMaskForeground_Default {
            get {
                return ResourceManager.GetString("OverlayMaskForeground_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayMask.Foreground.Disable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayMaskForeground_Disable {
            get {
                return ResourceManager.GetString("OverlayMaskForeground_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.OverlayMask.Foreground.MouseOver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayMaskForeground_MouseOver {
            get {
                return ResourceManager.GetString("OverlayMaskForeground_MouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.CurrentThemeName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThemeName {
            get {
                return ResourceManager.GetString("ThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultThickness.Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Thickness_Default {
            get {
                return ResourceManager.GetString("Thickness_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleOverlayTheme.DefaultThickness.Zero과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Thickness_Zero {
            get {
                return ResourceManager.GetString("Thickness_Zero", resourceCulture);
            }
        }
    }
}
