<Project>
    
  <!--Git-->
  <ItemGroup>
    <None Include="..\.gitignore">
      <Link>Git\.gitignore</Link>
    </None>
    <None Include="..\LICENSE">
      <Link>Git\LICENSE</Link>
    </None>
    <None Include="..\README.md">
      <Link>Git\README.md</Link>
    </None>
  </ItemGroup>
    
  <!--Props-->
  <ItemGroup>
    <None Include="..\Share\Props\Directory.Common.props">
      <Link>Directory.Common.props</Link>
    </None>
  </ItemGroup>
    
  <!--Resource-->
  <ItemGroup>
    <Resource Include="..\Share\Resource\Mask\Numeric1Box.png">
      <Link>Resource\Mask\Numeric1Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric2Box.png">
      <Link>Resource\Mask\Numeric2Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric3Box.png">
      <Link>Resource\Mask\Numeric3Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric4Box.png">
      <Link>Resource\Mask\Numeric4Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric5Box.png">
      <Link>Resource\Mask\Numeric5Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric6Box.png">
      <Link>Resource\Mask\Numeric6Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric7Box.png">
      <Link>Resource\Mask\Numeric7Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric8Box.png">
      <Link>Resource\Mask\Numeric8Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric9Box.png">
      <Link>Resource\Mask\Numeric9Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Numeric10Box.png">
      <Link>Resource\Mask\Numeric10Box.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\AlphaABox.png">
      <Link>Resource\Mask\AlphaABox.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\AlphaCBox.png">
      <Link>Resource\Mask\AlphaCBox.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\AlphaDBox.png">
      <Link>Resource\Mask\AlphaDBox.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\AlphaMBox.png">
      <Link>Resource\Mask\AlphaMBox.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\AlphaXBox.png">
      <Link>Resource\Mask\AlphaXBox.png</Link>
    </Resource>
  </ItemGroup>

</Project>
