<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Share\Props\Directory.Common.props" />
  <Import Project="Directory.Directory.props" />
  <PropertyGroup>
      
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ExampleList\NewFolder\" />
    <Folder Include="UserCustomControls\" />
    <Folder Include="SimpleOverlayTheme\Dummy\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SimpleOverlayTheme" Version="999.0.34" />
  </ItemGroup>

</Project>
