using SimpleOverlayTheme.Helpers;
using System.Windows.Controls;
using System.Windows;
using System.ComponentModel;

namespace SimpleOverlayTheme.AttachedBehavior.DataGrid
{
    [Localizable(true)]
    /// <summary>$Resources.ErrorCodes.ErrorMessage.Test1$</summary>
    internal static class AutoColumnStylesGenerater
    {
        public static void Attach(System.Windows.Controls.DataGrid dataGrid)
        {
            if (dataGrid == null)
                return;

            dataGrid.AutoGeneratingColumn -= OnAutoGeneratingColumn;
            dataGrid.AutoGeneratingColumn += OnAutoGeneratingColumn;
        }

        /// <summary> Detaches the style generation behavior from the specified <see cref="System.Windows.Controls.DataGrid"/>. </summary>
        /// <param name="dataGrid">The target <see cref="System.Windows.Controls.DataGrid"/> control.</param>
        public static void Detach(System.Windows.Controls.DataGrid dataGrid)
        {
            if (dataGrid == null)
                return;

            dataGrid.AutoGeneratingColumn -= OnAutoGeneratingColumn;
        }

        private static void OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (sender is not System.Windows.Controls.DataGrid dataGrid)
                return;

            Style? style = null;
            Style? editingStyle = null;

            switch (e.Column)
            {
                case DataGridTextColumn textColumn:
                    style = DataGridHelper.GetAutoGeneratedTextColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedTextColumnEditingStyle(dataGrid);
                    textColumn.ElementStyle = style;
                    textColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridCheckBoxColumn checkBoxColumn:
                    style = DataGridHelper.GetAutoGeneratedCheckBoxColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedCheckBoxColumnEditingStyle(dataGrid);
                    checkBoxColumn.ElementStyle = style;
                    checkBoxColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridComboBoxColumn comboBoxColumn:
                    style = DataGridHelper.GetAutoGeneratedComboBoxColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedComboBoxColumnEditingStyle(dataGrid);
                    comboBoxColumn.ElementStyle = style;
                    comboBoxColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridHyperlinkColumn hyperlinkColumn:
                    style = DataGridHelper.GetAutoGeneratedHyperlinkColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedHyperlinkColumnEditingStyle(dataGrid);
                    hyperlinkColumn.ElementStyle = style;
                    hyperlinkColumn.EditingElementStyle = editingStyle;
                    break;

                //case DataGridNumericUpDownColumn NumericUpDownColumn:
                //    style = DataGridHelper.GetAutoGeneratedNumericUpDownColumnStyle(dataGrid);
                //    editingStyle = DataGridHelper.GetAutoGeneratedNumericUpDownColumnEditingStyle(dataGrid);
                //    NumericUpDownColumn.ElementStyle = style;
                //    NumericUpDownColumn.EditingElementStyle = editingStyle;
                //    break;
            }
        }
    }
}