using SimpleOverlayTheme.Helpers;
using System.Windows.Controls;
using System.Windows;

namespace SimpleOverlayTheme.AttachedBehavior.DataGrid
{
    /// <summary xml:lang="en">
    /// <inheritdoc/>
    /// Provides behavior to apply custom styles automatically to auto-generated columns
    /// in a <see cref="System.Windows.Controls.DataGrid"/>.
    /// </summary>
    internal static class AutoColumnStylesGenerater
    {
        /// <summary>
        /// Attaches the style generation behavior to the specified <see cref="System.Windows.Controls.DataGrid"/>. <br/>
        /// This ensures that custom styles are applied to all auto-generated columns.
        /// </summary>
        /// <param name="dataGrid">The target <see cref="System.Windows.Controls.DataGrid"/> control.</param>
        public static void Attach(System.Windows.Controls.DataGrid dataGrid)
        {
            if (dataGrid == null)
                return;

            dataGrid.AutoGeneratingColumn -= OnAutoGeneratingColumn;
            dataGrid.AutoGeneratingColumn += OnAutoGeneratingColumn;
        }

        /// <summary> Detaches the style generation behavior from the specified <see cref="System.Windows.Controls.DataGrid"/>. </summary>
        /// <param name="dataGrid">The target <see cref="System.Windows.Controls.DataGrid"/> control.</param>
        public static void Detach(System.Windows.Controls.DataGrid dataGrid)
        {
            if (dataGrid == null)
                return;

            dataGrid.AutoGeneratingColumn -= OnAutoGeneratingColumn;
        }

        /// <summary>
        /// Handles the <see cref="System.Windows.Controls.DataGrid.AutoGeneratingColumn"/> event and applies
        /// appropriate styles based on the column type.
        ///   <list type="bullet">
        ///     <item><description>Text</description></item>
        ///     <item><description>CheckBox</description></item>
        ///     <item><description>ComboBox</description></item>
        ///     <item><description>Hyperlink</description></item>
        ///     <item><description>NumericUpDown(yet...)</description></item>
        ///   </list>
        /// </summary>
        /// <param name="sender">The source <see cref="System.Windows.Controls.DataGrid"/> triggering the event.</param>
        /// <param name="e">The column generation event arguments.</param>
        private static void OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (sender is not System.Windows.Controls.DataGrid dataGrid)
                return;

            Style? style = null;
            Style? editingStyle = null;

            switch (e.Column)
            {
                case DataGridTextColumn textColumn:
                    style = DataGridHelper.GetAutoGeneratedTextColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedTextColumnEditingStyle(dataGrid);
                    textColumn.ElementStyle = style;
                    textColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridCheckBoxColumn checkBoxColumn:
                    style = DataGridHelper.GetAutoGeneratedCheckBoxColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedCheckBoxColumnEditingStyle(dataGrid);
                    checkBoxColumn.ElementStyle = style;
                    checkBoxColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridComboBoxColumn comboBoxColumn:
                    style = DataGridHelper.GetAutoGeneratedComboBoxColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedComboBoxColumnEditingStyle(dataGrid);
                    comboBoxColumn.ElementStyle = style;
                    comboBoxColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridHyperlinkColumn hyperlinkColumn:
                    style = DataGridHelper.GetAutoGeneratedHyperlinkColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedHyperlinkColumnEditingStyle(dataGrid);
                    hyperlinkColumn.ElementStyle = style;
                    hyperlinkColumn.EditingElementStyle = editingStyle;
                    break;

                //case DataGridNumericUpDownColumn NumericUpDownColumn:
                //    style = DataGridHelper.GetAutoGeneratedNumericUpDownColumnStyle(dataGrid);
                //    editingStyle = DataGridHelper.GetAutoGeneratedNumericUpDownColumnEditingStyle(dataGrid);
                //    NumericUpDownColumn.ElementStyle = style;
                //    NumericUpDownColumn.EditingElementStyle = editingStyle;
                //    break;
            }
        }
    }
}