<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Share\Props\Directory.Common.props" />
  <PropertyGroup>
    <!--<TargetFrameworks>net8.0;net9.0</TargetFrameworks>-->
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>..\..\Bin\Tools\Ini2Xaml\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <PublishDir>..\..\Share\Tools\Ini2Xaml\$(TargetFramework)</PublishDir>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SimpleFileIO" Version="0.1.6" />
  </ItemGroup>

  <!-- Link Share Files -->

  <!--StringTable-->
  <ItemGroup>
    <Compile Include="..\..\Share\StringTable\Item\ThemeKeyPair\IniPair.cs" Condition="">
      <Link>StringTable\Item\ThemeKeyPair\IniPair.cs</Link>
    </Compile>
    <Compile Include="..\..\Share\StringTable\Item\ThemeKeyPair\ThemePair.cs">
      <Link>StringTable\Item\ThemeKeyPair\ThemePair.cs</Link>
    </Compile>
    <Compile Include="..\..\Share\StringTable\ThemeKey.cs">
      <Link>StringTable\ThemeKey.cs</Link>
    </Compile>
  </ItemGroup>
    

</Project>