<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <BaseOutputPath>$(SolutionDir)SimpleOverlayTheme\Build\</BaseOutputPath>
        <OutputPath>$(BaseOutputPath)CurrentThemeGeneraterToXaml\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <!-- not include .xml ... -->
        <NoWarn>$(NoWarn);NU5119</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="SimpleFileIO" Version="0.1.6" />
    </ItemGroup>
    <!--TEST-->
    <!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="dotnet &quot;$(OutDir)$(TargetName).dll&quot; &quot;$(OutDir)Current.ini&quot; &quot;$(OutDir)Current.xaml&quot;" />
    </Target>-->
</Project>