name: Job Process Format
description: >
  Generates text based on the job name and result.
inputs:
  jobs_and_results:
    description: >
      A JSON string containing job name and result pairs.
      Example: >
        [
          {
            "job_name": "Info And Check",
            "result": "success"
          },
          {
            "job_name": "Build Validation",
            "result": "failed"
          },
          {
            "job_name": "Auto Update Tag",
            "result": "needs.auto-update-tag.result"
          }
        ]
    required: true

outputs:
  output_result:
    description: make result job process
    value: ${{ steps.make-result-job-process.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Add Execute Permission for Scripts
      run: |
        # Add Execute Permission for Scripts
        chmod +x .scripts/format-string/header_wrapping.sh
      shell: bash

    - id: make-result-job-process
      run: |
        #Make Result Job Process
        temp_file=$(mktemp)

        # Params
        jobs_and_results='${{ inputs.jobs_and_results }}'  # Json

        echo $jobs_and_results | jq -c '.[]' | while read -r pair; do
          job_name=$(echo "$pair" | jq -r '.job_name')
          result=$(echo "$pair" | jq -r '.result')

          echo -e "\033[38;5;245m[${job_name}] ${result}\033[0m"

          if [[ "$result" == "success" ]]; then
            temp_string="\033[38;5;245m[$job_name] $result\033[0m"
          else
            temp_string="\033[38;5;245m[$job_name] \033[38;5;196m$result\033[0m"
          fi
          script_output=$( .scripts/format-string/header_wrapping.sh "$job_name" "$result" "${{ inputs.header_length }}" )
          echo "$script_output" >> "$temp_file"
        done

        # Output Setting
        multi_line_output=$(cat $temp_file)
        echo "output_result<<EOF" >> $GITHUB_OUTPUT
        echo "$multi_line_output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Delete temp file
        rm -f "$temp_file"
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: |
        # Remove Execute Permission for Scripts
        chmod -x .scripts/format-string/header_wrapping.sh
      shell: bash