name: Env Check
description: Validate and display Git environment variables and provided file paths
inputs:
  config:
    description: JSON-encoded configuration for the action
    required: true
    default: "{}"

runs:
  using: composite
  steps:

    - name: Add Execute Permission for Scripts
      run: chmod +x ${{ github.action_path }}/scripts/*.sh
      shell: bash

    - name: Parsing Config
      run: ${{ github.action_path }}/scripts/env-check.sh '${{ inputs.config }}'
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: chmod -x ${{ github.action_path }}/scripts/*.sh
      shell: bash