<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="GenerateOverlayThemeXaml"
            BeforeTargets="Build"
            >

        <Message Text="🔧 [SimpleOverlayTheme] current.ini → CurrentTheme.xaml 생성 중..." Importance="High" />

        <Exec Command='"$(MSBuildThisFileDirectory)..\..\tools\net8.0\SimpleOverlayTheme.CurrentThemeGeneraterToXaml.exe" "$(ProjectDir)current.ini" "$(ProjectDir)ThemeSystem\Current\CurrentTheme.xaml"' />
    </Target>

</Project>