using SimpleOverlayTheme.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;
using System.Windows;

namespace SimpleOverlayTheme.AttachedBehavior
{
    internal static class DataGridAutoColumnStylesGenerater
    {
        public static void Attach(DataGrid dataGrid)
        {
            if (dataGrid == null) return;

            dataGrid.AutoGeneratingColumn -= OnAutoGeneratingColumn;
            dataGrid.AutoGeneratingColumn += OnAutoGeneratingColumn;
        }

        public static void Detach(DataGrid dataGrid)
        {
            if (dataGrid == null) return;

            dataGrid.AutoGeneratingColumn -= OnAutoGeneratingColumn;
        }

        private static void OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (sender is not DataGrid dataGrid)
                return;

            Style? style = null;
            Style? editingStyle = null;

            switch (e.Column)
            {
                case DataGridTextColumn textColumn:
                    style = DataGridHelper.GetAutoGeneratedTextColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedTextColumnEditingStyle(dataGrid);
                    textColumn.ElementStyle = style;
                    textColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridCheckBoxColumn checkBoxColumn:
                    style = DataGridHelper.GetAutoGeneratedCheckBoxColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedCheckBoxColumnEditingStyle(dataGrid);
                    checkBoxColumn.ElementStyle = style;
                    checkBoxColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridComboBoxColumn comboBoxColumn:
                    style = DataGridHelper.GetAutoGeneratedComboBoxColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedComboBoxColumnEditingStyle(dataGrid);
                    comboBoxColumn.ElementStyle = style;
                    comboBoxColumn.EditingElementStyle = editingStyle;
                    break;

                case DataGridHyperlinkColumn hyperlinkColumn:
                    style = DataGridHelper.GetAutoGeneratedHyperlinkColumnStyle(dataGrid);
                    editingStyle = DataGridHelper.GetAutoGeneratedHyperlinkColumnEditingStyle(dataGrid);
                    hyperlinkColumn.ElementStyle = style;
                    hyperlinkColumn.EditingElementStyle = editingStyle;
                    break;
            }
        }
    }
}