using SimpleOverlayTheme.AttachedBehavior.DataGrid;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;

namespace SimpleOverlayTheme.Helpers
{
    /// <summary>
    /// Provides attached properties for customizing auto-generated column styles in a <see cref="DataGrid"/>. <br/>
    /// Supports setting element and editing styles for text, checkbox, combobox, and hyperlink columns,
    /// as well as enabling automatic style application behavior.
    /// </summary>
    public class DataGridHelper : APropertyHelper
    {
        ////////////////////////////////////////
        // AutoGeneratedCheckBoxColumnStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for styling auto-generated <see cref="DataGridCheckBoxColumn"/> elements. </summary>
        public static readonly DependencyProperty AutoGeneratedCheckBoxColumnStyleProperty
            = GeneratorProperty("AutoGeneratedCheckBoxColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the style to apply to an auto-generated <see cref="DataGridCheckBoxColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedCheckBoxColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedCheckBoxColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedCheckBoxColumnStyleProperty);

        /// <summary> Sets the style to apply to an auto-generated <see cref="DataGridCheckBoxColumn"/>. </summary>
        public static void SetAutoGeneratedCheckBoxColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedCheckBoxColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedCheckBoxColumnEditingStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for the editing style of auto-generated <see cref="DataGridCheckBoxColumn"/>. </summary>
        public static readonly DependencyProperty AutoGeneratedCheckBoxColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedCheckBoxColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the editing style for an auto-generated <see cref="DataGridCheckBoxColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedCheckBoxColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedCheckBoxColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedCheckBoxColumnEditingStyleProperty);

        /// <summary> Sets the editing style for an auto-generated <see cref="DataGridCheckBoxColumn"/>. </summary>
        public static void SetAutoGeneratedCheckBoxColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedCheckBoxColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedTextColumnStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for styling auto-generated <see cref="DataGridTextColumn"/> elements. </summary>
        public static readonly DependencyProperty AutoGeneratedTextColumnStyleProperty
            = GeneratorProperty("AutoGeneratedTextColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the style for an auto-generated <see cref="DataGridTextColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedTextColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedTextColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedTextColumnStyleProperty);

        /// <summary> Sets the style for an auto-generated <see cref="DataGridTextColumn"/>. </summary>
        public static void SetAutoGeneratedTextColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedTextColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedTextColumnEditingStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for the editing style of auto-generated <see cref="DataGridTextColumn"/>. </summary>
        public static readonly DependencyProperty AutoGeneratedTextColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedTextColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the editing style for an auto-generated <see cref="DataGridTextColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedTextColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedTextColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedTextColumnEditingStyleProperty);

        /// <summary> Sets the editing style for an auto-generated <see cref="DataGridTextColumn"/>. </summary>
        public static void SetAutoGeneratedTextColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedTextColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedComboBoxColumnStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for styling auto-generated <see cref="DataGridComboBoxColumn"/> elements. </summary>
        public static readonly DependencyProperty AutoGeneratedComboBoxColumnStyleProperty
            = GeneratorProperty("AutoGeneratedComboBoxColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the style for an auto-generated <see cref="DataGridComboBoxColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedComboBoxColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedComboBoxColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedComboBoxColumnStyleProperty);

        /// <summary> Sets the style for an auto-generated <see cref="DataGridComboBoxColumn"/>. </summary>
        public static void SetAutoGeneratedComboBoxColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedComboBoxColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedComboBoxColumnEditingStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for the editing style of auto-generated <see cref="DataGridComboBoxColumn"/>. </summary>
        public static readonly DependencyProperty AutoGeneratedComboBoxColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedComboBoxColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the editing style for an auto-generated <see cref="DataGridComboBoxColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedComboBoxColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedComboBoxColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedComboBoxColumnEditingStyleProperty);

        /// <summary> Sets the editing style for an auto-generated <see cref="DataGridComboBoxColumn"/>. </summary>
        public static void SetAutoGeneratedComboBoxColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedComboBoxColumnEditingStyleProperty, value);

        //////////////////////////////////////////
        //// AutoGeneratedNumericUpDownColumnStyle
        //////////////////////////////////////////

        /// <summary>
        /// Identifies the attached property that defines the style for an auto-generated NumericUpDown column in a <see cref="DataGrid"/>. <br/>
        /// This style is applied to the element view (non-editing) of the column.
        /// </summary>
        public static readonly DependencyProperty AutoGeneratedNumericUpDownColumnStyleProperty
            = GeneratorProperty("AutoGeneratedNumericUpDownColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the style applied to an auto-generated NumericUpDown column in a <see cref="DataGrid"/>. </summary>
        /// <param name="element">The target <see cref="UIElement"/>, typically a <see cref="DataGrid"/>.</param>
        /// <returns>The <see cref="Style"/> to use for displaying the column.</returns>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedNumericUpDownColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedNumericUpDownColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedNumericUpDownColumnStyleProperty);

        /// <summary> Sets the style to apply to an auto-generated NumericUpDown column in a <see cref="DataGrid"/>. </summary>
        /// <param name="element">The target <see cref="UIElement"/>, typically a <see cref="DataGrid"/>.</param>
        /// <param name="value">The <see cref="Style"/> to apply for the column's display (read-only) mode.</param>
        public static void SetAutoGeneratedNumericUpDownColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedNumericUpDownColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedNumericUpDownColumnEditingStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedNumericUpDownColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedNumericUpDownColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedNumericUpDownColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedNumericUpDownColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedNumericUpDownColumnEditingStyleProperty);

        /// <summary></summary>
        public static void SetAutoAutoGeneratedNumericUpDownColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedNumericUpDownColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedHyperlinkColumnStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for styling auto-generated <see cref="DataGridHyperlinkColumn"/> elements. </summary>
        public static readonly DependencyProperty AutoGeneratedHyperlinkColumnStyleProperty
            = GeneratorProperty("AutoGeneratedHyperlinkColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the style for an auto-generated <see cref="DataGridHyperlinkColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedHyperlinkColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedHyperlinkColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedHyperlinkColumnStyleProperty);

        /// <summary> Sets the style for an auto-generated <see cref="DataGridHyperlinkColumn"/>. </summary>
        public static void SetAutoGeneratedHyperlinkColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedHyperlinkColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedHyperlinkColumnEditingStyle
        ////////////////////////////////////////

        /// <summary> Identifies the attached property for the editing style of auto-generated <see cref="DataGridHyperlinkColumn"/>. </summary>
        public static readonly DependencyProperty AutoGeneratedHyperlinkColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedHyperlinkColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary> Gets the editing style for an auto-generated <see cref="DataGridHyperlinkColumn"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedHyperlinkColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedHyperlinkColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedHyperlinkColumnEditingStyleProperty);

        /// <summary> Sets the editing style for an auto-generated <see cref="DataGridHyperlinkColumn"/>. </summary>
        public static void SetAutoGeneratedHyperlinkColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedHyperlinkColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // UseAutoColumnStylesGenerater
        ////////////////////////////////////////

        /// <summary>
        /// Identifies the attached property that enables automatic style application
        /// via <see cref="AutoColumnStylesGenerater"/> during <see cref="DataGrid.AutoGeneratingColumn"/> event.
        /// </summary>
        public static readonly DependencyProperty UseAutoColumnStylesGeneraterProperty
            = GeneratorProperty("UseAutoColumnStylesGenerater",
                typeof(bool), typeof(DataGridHelper), false, OnUseAutoColumnStylesGeneraterChanged);

        /// <summary> Gets whether automatic style generation is enabled for the target <see cref="DataGrid"/>. </summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("UseAutoColumnStylesGenerater")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static bool GetUseAutoColumnStylesGenerater(UIElement element)
            => (bool)element.GetValue(UseAutoColumnStylesGeneraterProperty);

        /// <summary> Sets whether automatic style generation should be enabled for the target <see cref="DataGrid"/>. </summary>
        public static void SetUseAutoColumnStylesGenerater(UIElement element, bool value)
            => element.SetValue(UseAutoColumnStylesGeneraterProperty, value);

        /// <summary>
        /// Called when the <see cref="UseAutoColumnStylesGeneraterProperty"/> value changes. <br/>
        /// Attaches or detaches the <see cref="AutoColumnStylesGenerater"/> behavior to the <see cref="DataGrid"/>
        /// depending on whether the new value is <c>true</c> or <c>false</c>.
        /// </summary>
        /// <param name="d">The target <see cref="DependencyObject"/>, expected to be a <see cref="DataGrid"/>.</param>
        /// <param name="e">Event arguments containing the old and new values.</param>
        private static void OnUseAutoColumnStylesGeneraterChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is not DataGrid grid)
                return;

            if (e.NewValue is true)
                AutoColumnStylesGenerater.Attach(grid);
            else
                AutoColumnStylesGenerater.Detach(grid);
        }
    }
}
