using SimpleOverlayTheme.AttachedBehavior;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace SimpleOverlayTheme.Helpers
{
    //[StyleTypedProperty(Property = "AutoGeneratedCheckBoxColumnStyle", StyleTargetType = typeof(FrameworkElement))]
    //[StyleTypedProperty(Property = "AutoGeneratedCheckBoxColumnEditingStyle", StyleTargetType = typeof(FrameworkElement))]
    //[StyleTypedProperty(Property = "AutoGeneratedTextColumnStyle", StyleTargetType = typeof(FrameworkElement))]
    //[StyleTypedProperty(Property = "AutoGeneratedTextColumnEditingStyle", StyleTargetType = typeof(FrameworkElement))]
    //[StyleTypedProperty(Property = "AutoGeneratedComboBoxColumnStyle", StyleTargetType = typeof(FrameworkElement))]
    //[StyleTypedProperty(Property = "AutoGeneratedComboBoxColumnEditingStyle", StyleTargetType = typeof(FrameworkElement))]
    ////[StyleTypedProperty(Property = "AutoGeneratedNumericUpDownColumnStyle", StyleTargetType = typeof(FrameworkElement))]
    ////[StyleTypedProperty(Property = "AutoGeneratedNumericUpDownColumnEditingStyle", StyleTargetType = typeof(FrameworkElement))]
    //[StyleTypedProperty(Property = "AutoGeneratedHyperlinkColumnStyle", StyleTargetType = typeof(FrameworkElement))]
    //[StyleTypedProperty(Property = "AutoGeneratedHyperlinkColumnEditingStyle", StyleTargetType = typeof(FrameworkElement))]
    /// <summary>
    /// 
    /// </summary>
    public class DataGridHelper : APropertyHelper
    {
        ////////////////////////////////////////
        // AutoGeneratedCheckBoxColumnStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedCheckBoxColumnStyleProperty
            = GeneratorProperty("AutoGeneratedCheckBoxColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedCheckBoxColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedCheckBoxColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedCheckBoxColumnStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedCheckBoxColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedCheckBoxColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedCheckBoxColumnEditingStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedCheckBoxColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedCheckBoxColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedCheckBoxColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedCheckBoxColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedCheckBoxColumnEditingStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedCheckBoxColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedCheckBoxColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedTextColumnStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedTextColumnStyleProperty
            = GeneratorProperty("AutoGeneratedTextColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedTextColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedTextColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedTextColumnStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedTextColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedTextColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedTextColumnEditingStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedTextColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedTextColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedTextColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedTextColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedTextColumnEditingStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedTextColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedTextColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedComboBoxColumnStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedComboBoxColumnStyleProperty
            = GeneratorProperty("AutoGeneratedComboBoxColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedComboBoxColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedComboBoxColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedComboBoxColumnStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedComboBoxColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedComboBoxColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedComboBoxColumnEditingStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedComboBoxColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedComboBoxColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedComboBoxColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedComboBoxColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedComboBoxColumnEditingStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedComboBoxColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedComboBoxColumnEditingStyleProperty, value);

        //////////////////////////////////////////
        //// AutoGeneratedNumericUpDownColumnStyle
        //////////////////////////////////////////

        ///// <summary></summary>
        //public static readonly DependencyProperty AutoGeneratedNumericUpDownColumnStyleProperty
        //    = GeneratorProperty("AutoGeneratedNumericUpDownColumnStyle",
        //        typeof(Style), typeof(DataGridHelper));

        ///// <summary></summary>
        //[Browsable(true)]
        //[Category(nameof(DataGridHelper))]
        //[DisplayName("AutoGeneratedNumericUpDownColumnStyle")]
        //[AttachedPropertyBrowsableForType(typeof(DataGrid))]
        //public static Style? GetAutoGeneratedNumericUpDownColumnStyle(UIElement element)
        //    => (Style?)element.GetValue(AutoGeneratedNumericUpDownColumnStyleProperty);

        ///// <summary></summary>
        //public static void SetAutoGeneratedNumericUpDownColumnStyle(UIElement element, Style? value)
        //    => element.SetValue(AutoGeneratedNumericUpDownColumnStyleProperty, value);

        //////////////////////////////////////////
        //// AutoGeneratedNumericUpDownColumnEditingStyle
        //////////////////////////////////////////

        ///// <summary></summary>
        //public static readonly DependencyProperty AutoGeneratedNumericUpDownColumnEditingStyleProperty
        //    = GeneratorProperty("AutoGeneratedNumericUpDownColumnEditingStyle",
        //        typeof(Style), typeof(DataGridHelper));

        ///// <summary></summary>
        //[Browsable(true)]
        //[Category(nameof(DataGridHelper))]
        //[DisplayName("AutoGeneratedNumericUpDownColumnEditingStyle")]
        //[AttachedPropertyBrowsableForType(typeof(DataGrid))]
        //public static Style? GetAutoGeneratedNumericUpDownColumnEditingStyle(UIElement element)
        //    => (Style?)element.GetValue(AutoGeneratedNumericUpDownColumnEditingStyleProperty);

        ///// <summary></summary>
        //public static void SetAutoAutoGeneratedNumericUpDownColumnEditingStyle(UIElement element, Style? value)
        //    => element.SetValue(AutoGeneratedNumericUpDownColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedHyperlinkColumnStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedHyperlinkColumnStyleProperty
            = GeneratorProperty("AutoGeneratedHyperlinkColumnStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedHyperlinkColumnStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedHyperlinkColumnStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedHyperlinkColumnStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedHyperlinkColumnStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedHyperlinkColumnStyleProperty, value);

        ////////////////////////////////////////
        // AutoGeneratedHyperlinkColumnEditingStyle
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty AutoGeneratedHyperlinkColumnEditingStyleProperty
            = GeneratorProperty("AutoGeneratedHyperlinkColumnEditingStyle",
                typeof(Style), typeof(DataGridHelper));

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("AutoGeneratedHyperlinkColumnEditingStyle")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedHyperlinkColumnEditingStyle(UIElement element)
            => (Style?)element.GetValue(AutoGeneratedHyperlinkColumnEditingStyleProperty);

        /// <summary></summary>
        public static void SetAutoGeneratedHyperlinkColumnEditingStyle(UIElement element, Style? value)
            => element.SetValue(AutoGeneratedHyperlinkColumnEditingStyleProperty, value);

        ////////////////////////////////////////
        // UseAutoColumnStylesGenerater
        ////////////////////////////////////////

        /// <summary></summary>
        public static readonly DependencyProperty UseAutoColumnStylesGeneraterProperty
            = GeneratorProperty("UseAutoColumnStylesGenerater",
                typeof(bool), typeof(DataGridHelper), false, OnUseAutoColumnStylesGeneraterChanged);

        /// <summary></summary>
        [Browsable(true)]
        [Category(nameof(DataGridHelper))]
        [DisplayName("UseAutoColumnStylesGenerater")]
        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static bool GetUseAutoColumnStylesGenerater(UIElement element)
            => (bool)element.GetValue(UseAutoColumnStylesGeneraterProperty);

        /// <summary></summary>
        public static void SetUseAutoColumnStylesGenerater(UIElement element, bool value)
            => element.SetValue(UseAutoColumnStylesGeneraterProperty, value);

        private static void OnUseAutoColumnStylesGeneraterChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is not DataGrid grid)
                return;

            if (e.NewValue is true)
                DataGridAutoColumnStylesGenerater.Attach(grid);
            else
                DataGridAutoColumnStylesGenerater.Detach(grid);
        }
    }
}
