<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>
    <!-- Project -->
    <Nullable>enable</Nullable>
    <!-- Metadata & License -->
    <Company>Natel210</Company>
    <Authors>Natel210</Authors>
    <Title>$(AssemblyName)</Title>
    <Copyright>MIT</Copyright>
    <Description>
      <![CDATA[
        WPF resource DLL for simple themes.
        You can use it as basic WPF.
      ]]>
    </Description>
    <!-- Repository -->
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Natel210/SimpleOverlayThemeUI.git</RepositoryUrl>
  </PropertyGroup>
</Project>
