name: Exist Files
description: Check the existence of provided files and validate their paths
inputs:
  files:
    description: Space-separated list of file paths to check.
    required: true
    default: ""

runs:
  using: "composite"
  steps:

    - name: Add Execute Permission for Scripts
      run: chmod +x ${{ github.action_path }}/scripts/*.sh
      shell: bash

    - name: Run File Check Script
      run: ${{ github.action_path }}/scripts/exist-files.sh ${{ inputs.files }}
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: chmod -x ${{ github.action_path }}/scripts/*.sh
      shell: bash

