<Project>
    
  <!--Git-->
  <ItemGroup>
    <None Include="..\..\.gitignore">
      <Link>Git\.gitignore</Link>
    </None>
    <None Include="..\..\LICENSE">
      <Link>Git\LICENSE</Link>
    </None>
    <None Include="..\..\README.md">
      <Link>Git\README.md</Link>
    </None>
  </ItemGroup>
    
  <!--Props-->
  <ItemGroup>
    <None Include="..\..\Share\Props\Directory.Common.props">
      <Link>Directory.Common.props</Link>
    </None>
  </ItemGroup>
    
  <!--Publish-->
  <ItemGroup>
      <None Include="..\..\Share\Tools\Ini2Xaml\**\*.*">
          <Link>Publish\%(RecursiveDir)%(Filename)%(Extension)</Link>
      </None>
  </ItemGroup>
    
  <!--StringTable-->
  <ItemGroup>
    <Compile Include="..\..\Share\StringTable\Item\ThemeKeyPair\IniPair.cs">
      <Link>StringTable\Item\ThemeKeyPair\IniPair.cs</Link>
    </Compile>
    <Compile Include="..\..\Share\StringTable\Item\ThemeKeyPair\ThemePair.cs">
      <Link>StringTable\Item\ThemeKeyPair\ThemePair.cs</Link>
    </Compile>
    <Compile Include="..\..\Share\StringTable\ThemeKey.cs">
      <Link>StringTable\ThemeKey.cs</Link>
    </Compile>
  </ItemGroup>

</Project>
