<Project>
  <PropertyGroup>
    <!-- Default -->
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <!-- Project -->
    <Nullable>enable</Nullable>
    <DebugType>portable</DebugType>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <VersionPrefix>1.2.3</VersionPrefix>
    <!-- Path -->
    <BaseIntermediateOutputPath>..\Intermediate\$(AssemblyName)\</BaseIntermediateOutputPath>
    <OutputPath>..\Bin\$(Configuration)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <!-- Info -->
    <Authors>Natel210</Authors>
    <Company>$(Authors)</Company>
    <Copyright>© 2025 $(Authors)</Copyright>
    <!-- Build -->
    <TargetFramework>net8.0-windows7.0</TargetFramework>

  </PropertyGroup>
</Project>
