<Project>
    
  <!--Git-->
  <ItemGroup>
    <None Include="..\.gitignore">
      <Link>Git\.gitignore</Link>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
      <Link>Git\LICENSE</Link>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <Link>Git\README.md</Link>
    </None>
  </ItemGroup>


    
  <!--Props-->
  <ItemGroup>
    <None Include="..\Share\Props\Directory.Common.props">
      <Link>Directory.Common.props</Link>
    </None>
  </ItemGroup>
    
  <!--Resource-->
  <ItemGroup>
    <Resource Include="..\Share\Resource\Mask\Check.png">
      <Link>Resource\Mask\Check.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\CheckCircle.png">
      <Link>Resource\Mask\CheckCircle.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Minus.png">
      <Link>Resource\Mask\Minus.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\Plus.png">
      <Link>Resource\Mask\Plus.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\RadioButtonChecked.png">
      <Link>Resource\Mask\RadioButtonChecked.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\RadioButtonUnchecked.png">
      <Link>Resource\Mask\RadioButtonUnchecked.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\SortAsc.png">
      <Link>Resource\Mask\SortAsc.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\SortDesc.png">
      <Link>Resource\Mask\SortDesc.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\UnfoldLessHorizontal.png">
      <Link>Resource\Mask\UnfoldLessHorizontal.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\UnfoldMoreHorizontal.png">
      <Link>Resource\Mask\UnfoldMoreHorizontal.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\WindowClose.png">
      <Link>Resource\Mask\WindowClose.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\WindowRestore.png">
      <Link>Resource\Mask\WindowRestore.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\WindowMinimize.png">
      <Link>Resource\Mask\WindowMinimize.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\WindowMaximize.png">
      <Link>Resource\Mask\WindowMaximize.png</Link>
    </Resource>
  </ItemGroup>
    
  <!--StringTable-->
  <ItemGroup>
    <Compile Include="..\Share\StringTable\Item\ThemeKeyPair\IniPair.cs">
      <Link>StringTable\Item\ThemeKeyPair\IniPair.cs</Link>
    </Compile>
    <Compile Include="..\Share\StringTable\Item\ThemeKeyPair\ThemePair.cs">
      <Link>StringTable\Item\ThemeKeyPair\ThemePair.cs</Link>
    </Compile>
    <Compile Include="..\Share\StringTable\ThemeKey.cs">
      <Link>StringTable\ThemeKey.cs</Link>
    </Compile>
  </ItemGroup>
    
  <!--Tools-->
  <ItemGroup>
    <None Include="..\Share\Tools\Ini2Xaml\**\*.exe">
      <Pack>True</Pack>
      <PackagePath>tools\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <Link>Tools\Ini2Xaml\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>
    <!--Publish--><!--
    <ItemGroup>
        <None Include="..\..\Share\Tools\Ini2Xaml\**\*.*">
            <Link>Publish\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
    </ItemGroup>-->


    
    
    <!--<ItemGroup>
        <Content  Include="Documents\SimpleOverlayTheme.en.xml">
            <Pack>True</Pack>
            <PackagePath>SimpleOverlayTheme.xml</PackagePath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>SimpleOverlayTheme.xml</TargetPath>
        </Content >
        <Content  Include="Documents\SimpleOverlayTheme.en.xml">
            <Pack>True</Pack>
            <PackagePath>lib\$(TargetFramework)\en\SimpleOverlayTheme.xml</PackagePath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>en\SimpleOverlayTheme.xml</TargetPath>
        </Content >
        <Content  Include="Documents\SimpleOverlayTheme.kr.xml">
            <Pack>True</Pack>
            <PackagePath>lib\$(TargetFramework)\kr\SimpleOverlayTheme.xml</PackagePath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>kr\SimpleOverlayTheme.xml</TargetPath>
        </Content >
    </ItemGroup>-->


</Project>
