<Project>
    
  <!--Git-->
  <ItemGroup>
    <None Include="..\.gitignore">
      <Link>Git\.gitignore</Link>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
      <Link>Git\LICENSE</Link>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <Link>Git\README.md</Link>
    </None>
  </ItemGroup>

  <!--InternalSource-->
  <ItemGroup>
    <Content Include="SimpleOverlayTheme.targets">
      <Pack>True</Pack>
      <PackagePath>build\net8.0\</PackagePath>
      <Visible>true</Visible>
    </Content>
  </ItemGroup>
    
  <!--Props-->
  <ItemGroup>
    <None Include="..\Share\Props\Directory.Common.props">
      <Link>Directory.Common.props</Link>
    </None>
  </ItemGroup>
    
  <!--Resource-->
  <ItemGroup>
    <Resource Include="..\Share\Resource\Mask\check.png">
      <Link>Resource\Mask\check.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\close.png">
      <Link>Resource\Mask\close.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\downArrow.png">
      <Link>Resource\Mask\downArrow.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\maximize.png">
      <Link>Resource\Mask\maximize.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\minimize.png">
      <Link>Resource\Mask\minimize.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\minus.png">
      <Link>Resource\Mask\minus.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\plus.png">
      <Link>Resource\Mask\plus.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\restore.png">
      <Link>Resource\Mask\restore.png</Link>
    </Resource>
    <Resource Include="..\Share\Resource\Mask\upArrow.png">
      <Link>Resource\Mask\upArrow.png</Link>
    </Resource>
  </ItemGroup>
    
  <!--StringTable-->
  <ItemGroup>
    <Compile Include="..\Share\StringTable\Item\ThemeKeyPair\IniPair.cs">
      <Link>StringTable\Item\ThemeKeyPair\IniPair.cs</Link>
    </Compile>
    <Compile Include="..\Share\StringTable\Item\ThemeKeyPair\ThemePair.cs">
      <Link>StringTable\Item\ThemeKeyPair\ThemePair.cs</Link>
    </Compile>
    <Compile Include="..\Share\StringTable\ThemeKey.cs">
      <Link>StringTable\ThemeKey.cs</Link>
    </Compile>
  </ItemGroup>
    
  <!--Tools-->
  <ItemGroup>
    <None Include="..\Share\Tools\Ini2Xaml\SimpleOverlayTheme.Ini2Xaml.exe">
      <Pack>True</Pack>
      <PackagePath>tools\net8.0\SimpleOverlayTheme.Ini2Xaml.exe</PackagePath>
      <Link>Tools\Ini2Xaml\SimpleOverlayTheme.Ini2Xaml.exe</Link>
    </None>
  </ItemGroup>

</Project>
