<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Common.props" Condition="'$(SolutionDir)' == ''" />
  <Import Project="$(SolutionDir)\Directory.Common.props" Condition="'$(SolutionDir)' != ''" />
  <Import Project="Directory.Directory.props" />

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="SimpleFileIO" Version="0.1.6" />
    <PackageReference Include="WpfAnalyzers" Version="4.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="XAMLTools.MSBuild" Version="1.0.0-alpha0167">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
    
  <ItemGroup>
    <Compile Update="Resource\StringDictionary\ErrorCodes\ErrorMessage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorMessage.resx</DependentUpon>
    </Compile>
  </ItemGroup>
    
  <ItemGroup>
    <EmbeddedResource Update="Resource\StringDictionary\ErrorCodes\ErrorMessage.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
