<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Share\Props\Directory.Common.props" />
  <Import Project="Directory.Directory.props" />
  <!--<Import Project="Documents\Documents.targets" />-->
    
  <PropertyGroup>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Comments\**" />
    <EmbeddedResource Remove="Comments\**" />
    <None Remove="Comments\**" />
    <Page Remove="Comments\**" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="SimpleFileIO" Version="0.1.6" />
    <PackageReference Include="WpfAnalyzers" Version="4.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="XAMLTools.MSBuild" Version="1.0.0-alpha0167">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
    
  <ItemGroup>
    <Compile Update="Resource\StringDictionary\ErrorCodes\ErrorMessage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorMessage.resx</DependentUpon>
    </Compile>
  </ItemGroup>
    
  <ItemGroup>
    <EmbeddedResource Update="Resource\StringDictionary\ErrorCodes\ErrorMessage.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

    <!--<ItemGroup>
        <None Include="$(MSBuildProjectDirectory)\Documents\SimpleOverlayTheme.kr.xml"
              Condition="Exists('$(MSBuildProjectDirectory)\Documents\SimpleOverlayTheme.kr.xml')">
            <Pack>true</Pack>
            <PackagePath>$([System.String]::Format('lib\{0}\kr\SimpleOverlayTheme.xml', '$(TargetFramework)'))</PackagePath>
            <IncludeInPackage>true</IncludeInPackage>
        </None>
    </ItemGroup>--><!--
    <ItemGroup>
        <None Include="$(MSBuildProjectDirectory)\Documents\SimpleOverlayTheme.kr.xml"
              Condition="'$(TargetFramework)' == 'net8.0-windows'">
            <Pack>true</Pack>
            <PackagePath>lib/net8.0-windows/kr/SimpleOverlayTheme.xml</PackagePath>
        </None>
    </ItemGroup>-->
</Project>
