<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Common.props" Condition="'$(SolutionDir)' == ''" />
  <Import Project="$(SolutionDir)\Directory.Common.props" Condition="'$(SolutionDir)' != ''" />
  <Import Project="Directory.Directory.props" />
  <PropertyGroup>
    <Platforms>x64;AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SimpleFileIO" Version="0.1.6" />
  </ItemGroup>
  <!--TEST-->
  <!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet &quot;$(OutDir)$(TargetName).dll&quot; &quot;$(OutDir)Current.ini&quot; &quot;$(OutDir)Current.xaml&quot;" />
  </Target>-->
</Project>