name: Values Info Format
description: >
  Generates text based on values.
inputs:
  path_value_result:
    required: true
  git_value_result:
    required: true
  else_value_result:
    required: true

outputs:
  output_result:
    description: make value result
    value: ${{ steps.value-reuslt.outputs.output_result }}
runs:
  using: "composite"
  steps:
    - id: value-reuslt
      run: |
        # Values Info Format

        temp_file=$(mktemp)

        # Solution & Project
        echo -e "\033[38;5;245m● Solution & Project\033[0m" >> "$temp_file"
        if [[ -z "${{ inputs.path_value_result }}" ]]; then
          echo -e "\033[38;5;245m⚠️ Empty Path Value Result\033[0m" >> "$temp_file"
        else
          echo "${{ inputs.path_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
        fi

        # Git
        echo -e "\033[38;5;245m● Git\033[0m" >> "$temp_file"
        if [[ -z "${{ inputs.git_value_result }}" ]]; then
          echo -e "\033[38;5;245m⚠️ Empty Git Value Result\033[0m" >> "$temp_file"
        else
          echo "${{ inputs.git_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
        fi

        # Else
        echo -e "\033[38;5;245m● Else\033[0m" >> "$temp_file"
        if [[ -z "${{ inputs.else_value_result }}" ]]; then
          echo -e "\033[38;5;245m⚠️ Empty Else Value Result\033[0m" >> "$temp_file"
        else
          echo "${{ inputs.else_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
        fi

        # Output Setting
        multi_line_output=$(cat $temp_file)
        echo "output_result<<EOF" >> $GITHUB_OUTPUT
        echo "$multi_line_output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Delete temp file
        rm -f "$temp_file"

      shell: bash