name: Main CD
description: Push after

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write
  statuses: write

concurrency:
  group: main-push
  cancel-in-progress: false

env:
  TAG_PREFIX: "v"

jobs:
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Checkout Code with Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Actor and Changed Files
        id: check
        run: |
          SKIP=false
          
          if [[ "${{ github.actor }}" == "web-flow" ]]; then
        echo "Detected [web-flow]  P;- P;     UY   commit, skipping..."
            SKIP=true
          fi

          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          if echo "$CHANGED_FILES" | grep -qE "^(README\.md|docs/|\.github/ISSUE_TEMPLATE/|.*\.yml)$"; then
            echo "Only documentation or YAML files changed, skipping..."
            SKIP=true
          fi

          echo "skip=$SKIP" >> $GITHUB_OUTPUT
          
  versioning:
    # TEST
    needs: check-skip
    if: needs.check-skip.outputs.skip == 'false'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.update_version.outputs.version }}
    steps:
      - name: Git Check Out
        uses: actions/checkout@v4

      - name: Update Version
        id: update_version
        shell: bash
        run: |
          # Fetch latest tags
          git fetch --tags
          prefix="${{ env.TAG_PREFIX }}"
          latest_version=$(git tag | grep "^$prefix" | grep -E "^$prefix[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -n 1 || echo "${prefix}0.0.0")

          if [[ "$latest_version" =~ ^${prefix}([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            new_patch=$((patch + 1))
            new_version="$major.$minor.$new_patch"
          else
            new_version="0.0.1"
          fi

          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Update Tag
        run: |
          git fetch --tags
          TAG_NAME="${{ env.TAG_PREFIX }}${{ steps.update_version.outputs.version }}"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Deleting it..."
            git push --delete origin "$TAG_NAME"
            git tag -d "$TAG_NAME"
          fi
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

  build:
    runs-on: windows-latest
    needs: versioning
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.X"

      - name: Remove Test Project from Solution
        run: dotnet sln SimpleOverlayTheme.sln remove SimpleOverlayThemeExample/SimpleOverlayThemeExample.csproj

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear

      - name: Restore Only Main Project
        run: dotnet restore SimpleOverlayTheme/SimpleOverlayTheme.csproj

      - name: Build Only Main Project
        run: dotnet build SimpleOverlayTheme/SimpleOverlayTheme.csproj -c Release -p:Version="${{ needs.versioning.outputs.version }}" --no-restore

      - name: Ensure Artifacts Directory Exists
        run: |
          if (!(Test-Path -Path "artifacts")) {
            New-Item -ItemType Directory -Path "artifacts"
          }
        shell: pwsh

      - name: Publish Only Main Project
        run: |
          dotnet publish SimpleOverlayTheme/SimpleOverlayTheme.csproj -c Release -p:Version="${{ needs.versioning.outputs.version }}" -o artifacts/publish_output --no-build
          Compress-Archive -Path artifacts/publish_output -DestinationPath artifacts/publish_output.zip
        shell: pwsh

      - name: Pack NuGet Package
        run: dotnet pack -c Release -p:Version="${{ needs.versioning.outputs.version }}" -o artifacts
        shell: pwsh

      - name: Upload Release Package
        uses: actions/upload-artifact@v4
        with:
          name: release_package
          path: artifacts/publish_output.zip

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget_package
          path: artifacts/*.nupkg


  release:
    name: GitHub Release & NuGet Publish
    needs: [versioning, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Package
        uses: actions/download-artifact@v4
        with:
          name: release_package
          path: artifacts

      - name: Download NuGet Package
        uses: actions/download-artifact@v4
        with:
          name: nuget_package
          path: artifacts

      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_PREFIX }}${{ needs.versioning.outputs.version }}
          name: ${{ env.TAG_PREFIX }}${{ needs.versioning.outputs.version }}
          body: "Release version ${{ needs.versioning.outputs.version }}"
          files: artifacts/publish_output.zip

      - name: Push NuGet Package to NuGet.org
        run: |
          dotnet nuget push "artifacts/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_API_KEY }}" --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Push NuGet Package to GitHub Packages
        run: |
          dotnet nuget push "artifacts/*.nupkg" --source "https://nuget.pkg.github.com/Natel210/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
